### ISSUE TITLE
Docker load commands

### ISSUE THREAD

**Issue by ejwalk** [ibm-ecm/container-samples#1]
The CPE, ICN and CSS containers are not available on the docker store, they must be downloaded from PPA. Please correct the instructions to either provide the correct docker store urls or provide instructions for loading the tarball images provided in PPA.

**Comment by lpchitta** [comment]
Thanks for reporting. Modified the readme to download from PPA instead of docker store.

**Comment by ejwalk** [comment]
@lpchitta you also need a `docker load...` command after untaring the package that you download from PPA.

Made an error yesterday and used `docker import` instead, spun my wheels for a while...

**Comment by lpchitta** [comment]
@ejwalk Is this the command you used ?

docker image import <name of the file>

**Comment by ejwalk** [comment]
Yes, and that was incorrect, we needed to use docker image load

**Comment by ejwalk** [comment]
@lpchitta I figured out the right command by digging through the scripts provided with the new PIT (it's in getHostInfo.sh of all places, I think...)

**Comment by lpchitta** [comment]
@ejwalk Added docker image load -i <partnumber.tar> to readme. Thanks

**Comment by ghost** [comment]
@lpchitta This is still incorrect. The images need to be extracted from the <partnumber.tar>, then loaded. 


Using the Navigator images for example:

tar zxvf ICN_3.0.5_LNX_86_CONTAINER_ML.tgz

This will extract two tar.gz files. In this case, one is an image for Navigator SSO and the other is non-SSO.  

Then for each file, do

docker load < reallylongalphanumericstring.tar.gz

Which will generate about 40 lines of output similar to this:

 b8c891f0ffec: Loading layer [==================================================>]    120MB/120MB

Once this is done for both tar.gz files, initiating the **docker images** command will show this:

REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
navigator-sso       3.0.5               6b4bbb7d83dd        4 months ago        4.01GB
navigator           3.0.5               7288798734d0        4 months ago        4GB

**Comment by lpchitta** [comment]
Thank you. I just updated it. Please let me know for any changes.
