### ISSUE TITLE
The instruction for installing FileNet Content Manager on K8s seems incorrect

### ISSUE THREAD

**Issue by zymne** [ibm-ecm/container-samples#12]
Please, look at Step 5, there is a section dedicated to Security Context Constraints (SCC) which is **not applicable** to k8s and it's more likely related to OpenShift platform.

If so, should I make some corrections in yaml or elsewhere accordingly?

Here is the reference:
https://github.com/ibm-ecm/container-samples/blob/5.5.4/operator/platform/k8s/install.md

**Comment by TiloGit** [comment]
agree, also check the CP4A git as this has info on ignore SCC for K8.

**Comment by lpchitta** [comment]
Updated to remove SCC for K8s which is not required. 
closing ...
