### ISSUE TITLE
K8 install of 554 list oc commands

### ISSUE THREAD

**Issue by TiloGit** [ibm-ecm/container-samples#14]
https://github.com/ibm-ecm/container-samples/blob/5.5.4/operator/platform/k8s/install.md

Step 5: Deploy the operator manifest files to your cluster

**Comment by TiloGit** [comment]
also the example files don't have a namespace
https://github.com/ibm-ecm/container-samples/blob/5.5.4/operator/descriptors/5.5.4_iFix1/service_account.yaml

`Edit the namespace spec in the service_account.yaml and operator.yaml files.`

**Comment by lpchitta** [comment]
Fixed oc commands with kubectl for K8s.
We do not need to have namespace in example files as we documented to create namespace before you execute the sample files for operator.

**Comment by TiloGit** [comment]
thanks so we can ignore this:

2. Edit the namespace spec in the service_account.yaml and operator.yaml files. ?

**Comment by lpchitta** [comment]
Fixed the doc issue. closing.
