### ISSUE TITLE
need to set fncm_license?

### ISSUE THREAD

**Issue by TiloGit** [ibm-ecm/container-samples#15]
do we need to set: fncm_license in operator.yaml? in CP4A the sh script takes care about this.

**Comment by lpchitta** [comment]
Yes. We need to set the "accept" for fncm_license parameter in operator.yaml

**Comment by TiloGit** [comment]
thanks, please add to documentation

**Comment by lpchitta** [comment]
It is already mentioned in this iFixUpdate readme.

https://github.com/ibm-ecm/container-samples/blob/5.5.4/operator/platform/ocp/iFixesUpdate.md

Closing this issue.
