### ISSUE TITLE
missing info for 555, jar file for 

### ISSUE THREAD

**Issue by TiloGit** [ibm-ecm/container-samples#20]
the 555 branch doesn't have the info like 554. 
missing for example: 
https://github.com/ibm-ecm/container-samples/blob/5.5.4/operator/platform/k8s/install.md

What is filename expected for the postgres Jar file? (for a 555 deployment)

**Comment by lpchitta** [comment]
We have moved all the documentation to KC now starting this release 5.5.5
Here is the jar for postgres - > postgresql-42.2.9.jar

**Comment by TiloGit** [comment]
thanks, could you please share a link to the KC where I can find that info? (did a search on KC https://www.ibm.com/support/knowledgecenter/en/SSNW2F_5.5.0/ but 0 results)

**Comment by TiloGit** [comment]
well I guess this is the spot. https://www.ibm.com/support/knowledgecenter/SSNW2F_5.5.0/com.ibm.p8.containers.doc/containers_prep_operator_storage.htm
 but misses MS SQL and PostGres info

**Comment by lpchitta** [comment]
Yes that is correct. We will get that updated.
