### ISSUE TITLE
556 Operator fails to start

### ISSUE THREAD

**Issue by mccarthynj** [ibm-ecm/container-samples#23]
CPE 556 on AKS

Error: failed to create containerd task: OCI runtime create failed: container_linux.go:370: starting container process caused: exec: "--zap-time-encoding=iso8601": executable file not found in $PATH: unknown

Prior to 556, the container was home to two applications but 556 seems to have combined them into one.  I'm wondering if this is related to the apparent inability to find an executable.  Has anyone seen anything similar with 556?

**Comment by Vincent-Le** [comment]
@mccarthynj - Can you open a case with IBM support so that they can gather additional info and see if they can reproduce?

**Comment by mccarthynj** [comment]
RESOLVED - The issue was with the docker import into the artifactory back end.  Examination showed that a number of the layers were missing despite the load reporting success, including the layer that would have processed the parameter.
