### ISSUE TITLE
Disabling Network Policies 

### ISSUE THREAD

**Issue by timmy59100** [ibm-ecm/container-samples#25]
The operator creates a network policy "fncmdeploy-default-deny" that blocks all traffic in the namespace and to databases/ldap.
How can I disable that in the cluster definition YAML?

Thank you very much!

Best regards

**Comment by lpchitta** [comment]
Operator should be able to access the services with in the namespace with the network policy which was defined . 
This github is not monitoring regularly so , please open a CASE by contacting support to investigate the issue and close this issue.

**Comment by timmy59100** [comment]
With operator version 21.0.2 the network policy is fixed.
