### ISSUE TITLE
run CRD yaml file in K8s v1.22

### ISSUE THREAD

**Issue by mostafaabuelkhair** [ibm-ecm/container-samples#26]
hi, I have to install filenet 5.5.7 on k8s 1.22 
--> please find details about k8s version
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.3", GitCommit:"c92036820499fedefec0f847e2054d824aea6cd1", GitTreeState:"clean", BuildDate:"2021-10-29T02:41:56Z", GoVersion:"go1.16.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.2", GitCommit:"8b5a19147530eaac9476b0ab82980b4088bbc1b2", GitTreeState:"clean", BuildDate:"2021-09-15T21:32:41Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}

--> we already using latest version of container-sample files from this link "https://github.com/ibm-ecm/container-samples/tree/5.5.7" when we try to deploy "CustomResourceDefinition" from this sample file "fncm_v1_fncm_crd.yaml" it shown
$  kubectl create -f fncm_v1_fncm_crd.yaml
error: unable to recognize "fncm_v1_fncm_crd.yaml": no matches for kind "CustomResourceDefinition" in version "apiextensions.k8s.io/v1beta1" 
--> we modified the file because this api is deprecated and became "apiextensions.k8s.io/v1" and also found a mis-spelling in the pointed line 
openAPIV3Schema:
      properties:
        spec:
          properties:
            appVersion:
              type: string
            spec:
              properties:
                version:
                  type: string
              type: object
            status:
              description: CloudPakAutomationStatus defines the observed state of Automation
              properties:
                cpAutoStatus:
                  description: It will be as "OK when all objects are created successfully <---- we add another double quote to close the first one and add all text between both double quote like the following  
           status:
              description: CloudPakAutomationStatus defines the observed state of Automation
              properties:
                cpAutoStatus:
                  description: "It will be as OK when all objects are created successfully"
--> but when try to run the script it shown the following error
$ kubectl create -f fncm_v1_fncm_crd_2.yaml
error: error validating "fncm_v1_fncm_crd_2.yaml": error validating data: [ValidationError(CustomResourceDefinition.spec): unknown field "subresources" in io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1.CustomResourceDefinitionSpec, ValidationError(CustomResourceDefinition.spec): unknown field "validation" in io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1.CustomResourceDefinitionSpec, ValidationError(CustomResourceDefinition.spec): unknown field "version" in io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1.CustomResourceDefinitionSpec]; if you choose to ignore these errors, turn validation off with --validate=false

$ kubectl create -f fncm_v1_fncm_crd_2.yaml --validate=false
The CustomResourceDefinition "fncmclusters.fncm.ibm.com" is invalid: spec.versions[0].schema.openAPIV3Schema: Required value: schemas are required

--> also we found "validation:" field is used in this part became deprecated and replaced by "schema:" field according to the following link and also I modified the file and use schema field instead of validation field:
https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/#validation

validation:
   # openAPIV3Schema is the schema for validating custom objects.
   # in kube 1.14 schemas can be version specific
    openAPIV3Schema:

schema:
   # openAPIV3Schema is the schema for validating custom objects.
   # in kube 1.14 schemas can be version specific
    openAPIV3Schema:

--> but still  when try to deploy CRD it shown error the following error

$ kubectl create -f fncm_v1_fncm_crd.yaml
error: error validating "fncm_v1_fncm_crd.yaml": error validating data: [ValidationError(CustomResourceDefinition.spec): unknown field "schema" in io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1.CustomResourceDefinitionSpec, ValidationError(CustomResourceDefinition.spec): unknown field "subresources" in io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1.CustomResourceDefinitionSpec, ValidationError(CustomResourceDefinition.spec): unknown field "version" in io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1.CustomResourceDefinitionSpec]; if you choose to ignore these errors, turn validation off with --validate=false

$ kubectl create -f fncm_v1_fncm_crd.yaml --validate=false
The CustomResourceDefinition "fncmclusters.fncm.ibm.com" is invalid: spec.versions[0].schema.openAPIV3Schema: Required value: schemas are required

--> so could you please verify the CRD yaml files and try to deploy it in K8s version 1.22 and give us feed back

[fncm_v1_fncm_crd.txt](https://github.com/ibm-ecm/container-samples/files/7485749/fncm_v1_fncm_crd.txt)
[fncm_v1_fncm_crd_2.txt](https://github.com/ibm-ecm/container-samples/files/7485750/fncm_v1_fncm_crd_2.txt)

**Comment by lpchitta** [comment]
FNCM 5.5.7 does not support Kubernetes 1.22 . You will need to wait for next release of FNCM to gain support. 
Also , going forward please open support ticket to get your answers.
