### ISSUE TITLE
Readme

### ISSUE THREAD

**Issue by ejwalk** [ibm-ecm/container-samples#3]
The readme contains, 5 times, this link to github.ibm.com pages which is not public: https://github.ibm.com/ecm-container-service/ecm-container-monitoring.

**Comment by ejwalk** [comment]
@ktrinhibm making sure you saw this... I know you've got Grafana, was looking to see if Graphite is one of the supported modes or not and can't find a document that explains the range of valid values for the MON_ options and what they mean...

**Comment by lpchitta** [comment]
@ejwalk Addressed this issue now. Thanks
