### ISSUE TITLE
cors.xml allowedHeaders changed

### ISSUE THREAD

**Issue by TiloGit** [ibm-ecm/container-samples#4]
extShare/configDropins/overrides/cors.xml

**allowedHeaders** changed, check what client sends
```
 ECM-XSRF-Token (new)
 XSRFtoken (old)
```

Noticed with ICN 305 and this es version
```
version | "121"
build | "20181127-1636-121-jenkins"
```

**Comment by Vincent-Le** [comment]
@TiloGit - not sure if you are identifying an issue/defect, if yes, please open a case with IBM support to report the issue and obtain a fix (if needed).
