### ISSUE TITLE
Please provide MS SQL examples

### ISSUE THREAD

**Issue by TiloGit** [ibm-ecm/container-samples#6]
Could you please provide more example for MS SQL. 
For ICN yaml what are the values for: 
**ICNDBTYPE**

ICN create DB script for MS SQL.

**Comment by lpchitta** [comment]
ICNDBTYPE value is "mssql" for SQL Server.

**Comment by TiloGit** [comment]
thanks for the quick reply. Where is that document btw?

**Comment by lpchitta** [comment]
It was missing. So, now we have added here ..
https://github.com/ibm-ecm/container-samples/blob/5.5.3/k8s-yaml/README.md

**Comment by lpchitta** [comment]
Closing as we have updated it already
